services:
  - type: web
    name: n8n
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "N8N_ren&der@er59"
      - key: N8N_HOST
        value: "n8n_render.com"
      - key: WEBHOOK_TUNNEL_URL
        value: "https://n8n_render.com"
      - key: GENERIC_TIMEZONE
        value: "Europe/Paris"
